name = "GregTech CEu Modern Community Pack"
author = "ursamina"
version = "1.12.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77089b977ec28678d1b82e846747345d7f3f2fd47eb470d59702285a73a0e6b5"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
