name = "GregTech CEu Modern Community Pack"
author = "ursamina"
version = "1.13.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86b8b8d73f99a70138ee23e9bd5cfd67067e28f21933138a3751d9d51508c292"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
