name = "GregTech CEu Modern Community Pack"
author = "ursamina"
version = "1.14.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44585fef7290e7008ad3c8c2d3952c4fd157b8047c5709479b192a2bf9f034d0"

[versions]
forge = "47.4.6"
minecraft = "1.20.1"
