name = "GregTech CEu Modern Community Pack"
author = "ursamina"
version = "1.14.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44851173b76d9afcbf36d938964a63377079dc781092e459b3917f335b8f5ece"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
